files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 1B8480D9C25B983523733515ED7D462C
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1B8480D9C25B983523733515ED7D462C
- generatedChecksum: 1FE8F55543D36A22F134CFADBB013A69
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FE8F55543D36A22F134CFADBB013A69
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5192896384BDEA0B08CDCE5833E31223
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5192896384BDEA0B08CDCE5833E31223
- generatedChecksum: 01DCC998E5EE8CEEECE71AE87264A44F
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 01DCC998E5EE8CEEECE71AE87264A44F
- generatedChecksum: 085AD21E69A015135F99F9AE4E244A69
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 085AD21E69A015135F99F9AE4E244A69
- generatedChecksum: 53F9FD402C109D0E010853BB8761E842
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 53F9FD402C109D0E010853BB8761E842
- generatedChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
  logicalPath: config/pic32mz_ef_sk/system/console
  name: sys_console.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
- generatedChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
  logicalPath: config/pic32mz_ef_sk/system/console
  name: sys_console_local.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
- generatedChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
  logicalPath: config/pic32mz_ef_sk/system/console
  name: sys_console_uart.c
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
- generatedChecksum: 767495C6A39617A915D8107093DC1A72
  logicalPath: config/pic32mz_ef_sk/system/console
  name: sys_console_uart.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 767495C6A39617A915D8107093DC1A72
- generatedChecksum: 5D10B9438117B64220180660AB022150
  logicalPath: config/pic32mz_ef_sk/system/console
  name: sys_console_uart_definitions.h
  physicalPath: system/console/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D10B9438117B64220180660AB022150
- generatedChecksum: 68C0D499B9EDAA3BFD7E131A48514212
  logicalPath: config/pic32mz_ef_sk/system/debug
  name: sys_debug.c
  physicalPath: system/debug/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 68C0D499B9EDAA3BFD7E131A48514212
- generatedChecksum: B8C6C7356AC7841AECC7C779040F745C
  logicalPath: config/pic32mz_ef_sk/system/debug
  name: sys_debug_local.h
  physicalPath: system/debug/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8C6C7356AC7841AECC7C779040F745C
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mz_ef_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A9C595E0E5A92D2B85C18D2A27597B84
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C595E0E5A92D2B85C18D2A27597B84
- generatedChecksum: 9E6FBD88FCCB553D64D4536902580AB5
  logicalPath: config/pic32mz_ef_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E6FBD88FCCB553D64D4536902580AB5
- generatedChecksum: 19E9338723DF5AD4ACD6B52429B8AC83
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 19E9338723DF5AD4ACD6B52429B8AC83
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_ef_sk/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_ef_sk/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C730E56D028FBC00572DDBD3E67C7C7
- generatedChecksum: 86D499749C924875389705AA3D0C9FD7
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 86D499749C924875389705AA3D0C9FD7
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
  logicalPath: config/pic32mz_ef_sk/system/console
  name: sys_console.h
  physicalPath: system/console
  security: NON_SECURE
  type: HEADER
  userChecksum: 91CB36F6EC29DAA7C584282A875E5CBA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mz_ef_sk/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_ef_sk/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_ef_sk/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_ef_sk/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: C734E3299D476FDDB140E61BA3B5C31B
  logicalPath: config/pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C734E3299D476FDDB140E61BA3B5C31B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
