files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: 65F5B99DAB8ECAC3CB0624E73CA6E0A0
  logicalPath: config/pic32mz_ef_sk/system/fs/fat_fs/hardware_access
  name: diskio.c
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65F5B99DAB8ECAC3CB0624E73CA6E0A0
- generatedChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
  logicalPath: config/pic32mz_ef_sk/driver/memory
  name: drv_memory.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
- generatedChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
  logicalPath: config/pic32mz_ef_sk/driver/memory
  name: drv_memory_file_system.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
- generatedChecksum: F74818AF60798C8B82255A88755ED9DA
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26.c
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F74818AF60798C8B82255A88755ED9DA
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: D991CF8C9FF9C5452F5D78B4D7BC766E
  logicalPath: config/pic32mz_ef_sk/system/fs/fat_fs/file_system
  name: ff.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: D991CF8C9FF9C5452F5D78B4D7BC766E
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config/pic32mz_ef_sk/system/fs/fat_fs/file_system
  name: ffunicode.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: 4BEB23CC6FC163AE228DC7800EB61272
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BEB23CC6FC163AE228DC7800EB61272
- generatedChecksum: BBF0D9D99B5764809C285383BA2C43C8
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BBF0D9D99B5764809C285383BA2C43C8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
  logicalPath: config/pic32mz_ef_sk/peripheral/cache
  name: plib_cache.c
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
- generatedChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
  logicalPath: config/pic32mz_ef_sk/peripheral/cache
  name: plib_cache_local.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
- generatedChecksum: 0DA10C8889278A796D0EE4C6096B57C3
  logicalPath: config/pic32mz_ef_sk/peripheral/cache
  name: plib_cache_pic32mz.S
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0DA10C8889278A796D0EE4C6096B57C3
- generatedChecksum: 8B20AB1AA3A63B10E688D7ECC220B402
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8B20AB1AA3A63B10E688D7ECC220B402
- generatedChecksum: 4D6CD10836C28BC125338FC6051943BB
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4D6CD10836C28BC125338FC6051943BB
- generatedChecksum: 373E2B1E8CD59960940BAA5CA2555989
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 373E2B1E8CD59960940BAA5CA2555989
- generatedChecksum: A2E207D459736D20CF2C38D551EE1A99
  logicalPath: config/pic32mz_ef_sk/peripheral/sqi
  name: plib_sqi1.c
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2E207D459736D20CF2C38D551EE1A99
- generatedChecksum: 47204A328D6218B0241B5993D3198668
  logicalPath: config/pic32mz_ef_sk/system/cache
  name: sys_cache.c
  physicalPath: system/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47204A328D6218B0241B5993D3198668
- generatedChecksum: 64197587C5A197FD05E94AB039A2DD66
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64197587C5A197FD05E94AB039A2DD66
- generatedChecksum: 1F79CD9E378D98E657FCEB0552B2B659
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs_fat_interface.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F79CD9E378D98E657FCEB0552B2B659
- generatedChecksum: 1115692CC0E3DF70C0007627FCAC6FFA
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs_media_manager.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1115692CC0E3DF70C0007627FCAC6FFA
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 22CA1BA8315F3E404A8BD8B5BD0C04CF
  logicalPath: config/pic32mz_ef_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 22CA1BA8315F3E404A8BD8B5BD0C04CF
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: FC782AD00DD7AE406925CAE213C45DA3
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: FC782AD00DD7AE406925CAE213C45DA3
- generatedChecksum: 8B9321D05DFD09922E3C999BFD53E7DF
  logicalPath: config/pic32mz_ef_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B9321D05DFD09922E3C999BFD53E7DF
- generatedChecksum: FB8F66B977819B28C3C7BF6A922FF82E
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FB8F66B977819B28C3C7BF6A922FF82E
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
  logicalPath: config/pic32mz_ef_sk
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config/pic32mz_ef_sk/system/fs/fat_fs/hardware_access
  name: diskio.h
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_ef_sk/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_ef_sk/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 64EA07D284832B8E56C403AE90B52CD5
  logicalPath: config/pic32mz_ef_sk/driver/memory
  name: drv_memory.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: 64EA07D284832B8E56C403AE90B52CD5
- generatedChecksum: B37635A7E5516B08B10146BB58A6C2D9
  logicalPath: config/pic32mz_ef_sk/driver/memory
  name: drv_memory_definitions.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: B37635A7E5516B08B10146BB58A6C2D9
- generatedChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
  logicalPath: config/pic32mz_ef_sk/driver/memory
  name: drv_memory_local.h
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
- generatedChecksum: B15A01670F19BDF4E85A411D4E7513D9
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: B15A01670F19BDF4E85A411D4E7513D9
- generatedChecksum: D712283D4ED135C84E162B40760A9C23
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26_definitions.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: D712283D4ED135C84E162B40760A9C23
- generatedChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
  logicalPath: config/pic32mz_ef_sk/driver/sst26
  name: drv_sst26_local.h
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: HEADER
  userChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
- generatedChecksum: 187EFA39553617C34D670BFA3AA15C5F
  logicalPath: config/pic32mz_ef_sk/system/fs/fat_fs/file_system
  name: ff.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 187EFA39553617C34D670BFA3AA15C5F
- generatedChecksum: 6E11D27FFFCF7C7BB6AE5B10AD60786C
  logicalPath: config/pic32mz_ef_sk/system/fs/fat_fs/file_system
  name: ffconf.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 6E11D27FFFCF7C7BB6AE5B10AD60786C
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 37885E3505BF5B0FD6AFE768807361C1
  logicalPath: config/pic32mz_ef_sk/peripheral/cache
  name: plib_cache.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 37885E3505BF5B0FD6AFE768807361C1
- generatedChecksum: 3D2558D7758EF020BBF792820203C0A2
  logicalPath: config/pic32mz_ef_sk/peripheral/cache
  name: plib_cache_pic32mz.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D2558D7758EF020BBF792820203C0A2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: FFF8E458FD7BB6E5CED45D1549F80253
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FFF8E458FD7BB6E5CED45D1549F80253
- generatedChecksum: 83A29BB1714DD4AF71B7176C4A487262
  logicalPath: config/pic32mz_ef_sk/peripheral/sqi
  name: plib_sqi1.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: 83A29BB1714DD4AF71B7176C4A487262
- generatedChecksum: BA2AAEA19E581F59C1E78E73982F7C78
  logicalPath: config/pic32mz_ef_sk/peripheral/sqi
  name: plib_sqi_common.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: BA2AAEA19E581F59C1E78E73982F7C78
- generatedChecksum: AFAAF7D896D57569CA4CF73BB3339481
  logicalPath: config/pic32mz_ef_sk/system/cache
  name: sys_cache.h
  physicalPath: system/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: AFAAF7D896D57569CA4CF73BB3339481
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mz_ef_sk/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: 64F22D21B48A241C02F4D9DEB576D5B6
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 64F22D21B48A241C02F4D9DEB576D5B6
- generatedChecksum: 0D9FE9035E3AA8082C5657240106F2DC
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs_fat_interface.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D9FE9035E3AA8082C5657240106F2DC
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: C57A4CE87A00A891A99A4248ADEE0D2E
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs_media_manager.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: C57A4CE87A00A891A99A4248ADEE0D2E
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config/pic32mz_ef_sk/system/fs
  name: sys_fs_media_manager_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_ef_sk/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_ef_sk/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_ef_sk/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config/pic32mz_ef_sk/system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_ef_sk/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: C734E3299D476FDDB140E61BA3B5C31B
  logicalPath: config/pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C734E3299D476FDDB140E61BA3B5C31B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_ef_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_ef_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mz_ef_sk/system/fs/fat_fs/file_system;../src/config/pic32mz_ef_sk/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
