files:
- generatedChecksum: E4894B6355AF41AED546E4C6C20005C1
  logicalPath: FreeRTOS/Source
  name: FreeRTOS_tasks.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4894B6355AF41AED546E4C6C20005C1
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: 4490B523D4D89767AF3FE31B825F7F6D
  logicalPath: FreeRTOS/Source
  name: croutine.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4490B523D4D89767AF3FE31B825F7F6D
- generatedChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
  logicalPath: FreeRTOS/Source
  name: event_groups.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: CF89BE92AE72229779903C2E9A760455
  logicalPath: config/pic32mz_ef_sk
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CF89BE92AE72229779903C2E9A760455
- generatedChecksum: 31CEE4650E24C72160696DF93B55B48D
  logicalPath: FreeRTOS/Source/portable/MemMang
  name: heap_1.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31CEE4650E24C72160696DF93B55B48D
- generatedChecksum: 3391DEB8B0F66925418A6C620387AC2E
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3391DEB8B0F66925418A6C620387AC2E
- generatedChecksum: 32FA4FDE9FEB0B5085634674D685A47F
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 32FA4FDE9FEB0B5085634674D685A47F
- generatedChecksum: 37C07CDED6C2046B2A46285FF89E8668
  logicalPath: config/pic32mz_ef_sk
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 37C07CDED6C2046B2A46285FF89E8668
- generatedChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
  logicalPath: FreeRTOS/Source
  name: list.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_freertos.c
  physicalPath: osal
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
- generatedChecksum: 393FFE41A2801A5F7DB58B4328149072
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 393FFE41A2801A5F7DB58B4328149072
- generatedChecksum: C9677ADEC7B436C369D41AA33CA1E224
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C9677ADEC7B436C369D41AA33CA1E224
- generatedChecksum: 61F98F4B15B51C9E7F47D64FD51B3619
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 61F98F4B15B51C9E7F47D64FD51B3619
- generatedChecksum: DEC6A7ED50266C07DAEBBAC8BD7982B3
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: DEC6A7ED50266C07DAEBBAC8BD7982B3
- generatedChecksum: 496F6DC7F636C475EFD5831B4202C13D
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MZ
  name: port.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ
  security: NON_SECURE
  type: SOURCE
  userChecksum: 496F6DC7F636C475EFD5831B4202C13D
- generatedChecksum: DF45E3DDDEC2F56707A9CBFBE9B8F3FD
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MZ
  name: port_asm.S
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF45E3DDDEC2F56707A9CBFBE9B8F3FD
- generatedChecksum: 13259EE43A731BF0F46EA946229027BF
  logicalPath: FreeRTOS/Source
  name: queue.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13259EE43A731BF0F46EA946229027BF
- generatedChecksum: A9BDA97498BEA85049883F48FB1094A0
  logicalPath: FreeRTOS/Source
  name: stream_buffer.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: A9BDA97498BEA85049883F48FB1094A0
- generatedChecksum: null
  logicalPath: ''
  name: task1.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task2.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task3.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task4.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 923B2290DA9C0164D4F2DE731494E321
  logicalPath: config/pic32mz_ef_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 923B2290DA9C0164D4F2DE731494E321
- generatedChecksum: 2811D7C532CEFF995F8697FCED6A1C34
  logicalPath: FreeRTOS/Source
  name: timers.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2811D7C532CEFF995F8697FCED6A1C34
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
  logicalPath: FreeRTOS/Source/include
  name: FreeRTOS.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
- generatedChecksum: 2524A4F234E453FB678B881E9862D605
  logicalPath: config/pic32mz_ef_sk
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2524A4F234E453FB678B881E9862D605
- generatedChecksum: E44F224CDF5B12B127F4CF2B074AD35D
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MZ
  name: ISR_Support.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ
  security: NON_SECURE
  type: HEADER
  userChecksum: E44F224CDF5B12B127F4CF2B074AD35D
- generatedChecksum: 1A0CDAC1576FDC743BCF901E93EA3963
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 1A0CDAC1576FDC743BCF901E93EA3963
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mz_ef_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 4B11D1A616E95BDD37123685C8434FCF
  logicalPath: FreeRTOS/Source/include
  name: croutine.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B11D1A616E95BDD37123685C8434FCF
- generatedChecksum: D3CBBC8204B437DE9CCE9B6A668103C1
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D3CBBC8204B437DE9CCE9B6A668103C1
- generatedChecksum: ACB7AD12FD525895ABA47C26F4F9A683
  logicalPath: FreeRTOS/Source/include
  name: deprecated_definitions.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: ACB7AD12FD525895ABA47C26F4F9A683
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: DE52B71A2D274138117243B700F40B11
  logicalPath: FreeRTOS/Source/include
  name: event_groups.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: DE52B71A2D274138117243B700F40B11
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
  logicalPath: FreeRTOS/Source/include
  name: list.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
- generatedChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
  logicalPath: FreeRTOS/Source/include
  name: message_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
- generatedChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
  logicalPath: FreeRTOS/Source/include
  name: mpu_prototypes.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
- generatedChecksum: 2ECEDD5114F296955777187904C449C7
  logicalPath: FreeRTOS/Source/include
  name: mpu_wrappers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2ECEDD5114F296955777187904C449C7
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 167A43EFF8A31441EBF85AC77958A30B
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 167A43EFF8A31441EBF85AC77958A30B
- generatedChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
  logicalPath: config/pic32mz_ef_sk/osal
  name: osal_freertos.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 1DBEF3D35B3D6D4398D444CB951D8FB3
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 1DBEF3D35B3D6D4398D444CB951D8FB3
- generatedChecksum: 9042B36EACA99ACB163ED84CD9969944
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 9042B36EACA99ACB163ED84CD9969944
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
  logicalPath: FreeRTOS/Source/include
  name: portable.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
- generatedChecksum: 94F2A78A46AC9F36C974B8E7BA09919F
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MZ
  name: portmacro.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ
  security: NON_SECURE
  type: HEADER
  userChecksum: 94F2A78A46AC9F36C974B8E7BA09919F
- generatedChecksum: 99A9BD4D90230B49C97BBCEE121C1182
  logicalPath: FreeRTOS/Source/include
  name: projdefs.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 99A9BD4D90230B49C97BBCEE121C1182
- generatedChecksum: F917F55E280C54C23A7541A76AC34225
  logicalPath: FreeRTOS/Source/include
  name: queue.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: F917F55E280C54C23A7541A76AC34225
- generatedChecksum: D7426A4807316E4BB5540458F6F4C68F
  logicalPath: FreeRTOS/Source/include
  name: semphr.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: D7426A4807316E4BB5540458F6F4C68F
- generatedChecksum: 634A3DF879F184ABC5F96107F46AC4B2
  logicalPath: FreeRTOS/Source/include
  name: stack_macros.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 634A3DF879F184ABC5F96107F46AC4B2
- generatedChecksum: A652AC7D4938BE16F535BA3C90C86463
  logicalPath: FreeRTOS/Source/include
  name: stream_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A652AC7D4938BE16F535BA3C90C86463
- generatedChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
  logicalPath: FreeRTOS/Source/include
  name: task.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
- generatedChecksum: null
  logicalPath: ''
  name: task1.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task2.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task3.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task4.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 41176F771D22559EFCE82398FCF33668
  logicalPath: FreeRTOS/Source/include
  name: timers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 41176F771D22559EFCE82398FCF33668
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: C734E3299D476FDDB140E61BA3B5C31B
  logicalPath: config/pic32mz_ef_sk
  name: p32MZ2048EFH144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: C734E3299D476FDDB140E61BA3B5C31B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mz_ef_sk;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mz_ef_sk;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MZ;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
